package:
    name: nilm_metadata_s14pe
    version: "0.2.5.dev1"
source:
    path: ..
build:
    noarch: python
    
requirements:
    host:
        - python 
        - setuptools
    run:
        - PyYAML
        - pandas
        - six
extra:
    copy_test_source_files: true
    final: true
